[build]
  command = "npm run build"
  publish = "out"

# No plugins needed for static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
